Enforced Airbnb style guide with Eslint
pavelkeyzik/pr-approve-generator pull request #19
Opened 2022-10-22 15:15 UTC by Iam-SilentEyes

Added scripts  "lint" and "lint-fix" for easy use

2022-10-23 16:11 UTC, pavelkeyzik requested changes
Hey @Iam-SilentEyes 👋 Thanks for working on this feature. I'm so happy to see this PR. May I ask you to fix some little issues from comments and one more thing.

We're using Prettier with default configuration and when Prettier formats file, it ignores Airbnb configuration. That way we get a problems like when we save file, Prettier converts `''` to `""` and ESLint is angry 😆

2022-10-23 16:11 UTC, pavelkeyzik commented on .eslintrc.json
> +{
Can we fix tab spaces here? We use 2, and in my case when I save this file, prettier will update format

2022-10-23 16:11 UTC, pavelkeyzik commented on src/core/messages.js
> +export default messages;
Can we ignore this rule? From my experience default export always makes issues with the naming when someone use it like `import messagesList from 'messages';`. Sometimes it's harder to keep in mind that messagesList it's just messages and it's harder to refactor that

2022-10-23 16:13 UTC, pavelkeyzik commented on .vscode/extensions.json
> +        "mflo999.lintel",
Can you remove that from recommendations? As the configuration helper is not something everyone should have while working on the project, so I guess it's not something that should live in a recommendations section 😊

2022-10-26 13:16 UTC, pavelkeyzik commented
Hey @Iam-SilentEyes 👋  I saw you commited fixes, but there is still some errors. Just want to know if you're still workgin on that 😊

2022-10-27 06:39 UTC, pavelkeyzik requested changes

2022-10-27 06:39 UTC, pavelkeyzik commented on .vscode/extensions.json
> +{
Can we remove this file, as we don't have any recommendations here?

2022-10-27 06:39 UTC, pavelkeyzik commented on .eslintrc.json
> +    {
Tab size is 4 spaces here, instead of 2. Can you fix that?

2022-10-27 06:39 UTC, pavelkeyzik commented on src/core/messages.js
> +  'Nice job',
ESLint changes `""` to `''`, but Prettier changes to `''`. Prettier runs after ESLint, so the problem will be that when we save file, our quotes will be `''` and the ESLint will have errors

2022-10-29 07:19 UTC, Iam-SilentEyes commented
Hey @pavelkeyzik is anything wrong again ? If not maybe you can accept it :)

2022-10-30 07:07 UTC, pavelkeyzik commented
As you may see, our PR contains new ESLint configuration, but at the same time we have changes in our files. We don't want it, as we should configure ESLint to follow project styles. Also, ESLint should work with Prettier. For example, you can see that emojis file is updated, because ESLint changes "" to '', but we use Prettier and it will update '' to "" after ESLint updates. It means that it's impossible to save file with new ESLint rule as it's conflicts with Prettier. Can you try to install VSCode extension and configure it to format code on save file? That way you should see a problem

2022-11-01 17:50 UTC, closed without merging